# Generated by Django 5.2.12 on 2026-04-02 12:55

import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userteam_transferrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_api_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=150)),
                ('position', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, max_length=100)),
                ('team_name', models.CharField(blank=True, max_length=150)),
                ('cost', models.DecimalField(decimal_places=2, default=5000000.0, max_digits=12)),
            ],
            options={
                'db_table': 'Players',
            },
        ),
        migrations.AddField(
            model_name='userteam',
            name='formation',
            field=models.CharField(default='4-4-2', max_length=20),
        ),
        migrations.AlterField(
            model_name='userteam',
            name='budget',
            field=models.DecimalField(decimal_places=2, default=100000000.0, max_digits=12),
        ),
    ]
