# Generated by Django 6.0.4 on 2026-04-24 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_player_userteam_formation_alter_userteam_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminprofile',
            name='two_factor_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='two_factor_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='team_api_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='two_factor_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='two_factor_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userteam',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
