# Generated by Django 6.0.4 on 2026-04-24 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_adminprofile_two_factor_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userteam',
            name='processed_matchweeks',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
