# Generated by Django 6.0.4 on 2026-04-24 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userteam_processed_matchweeks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userteam',
            name='free_transfers',
        ),
    ]
