# Generated by Django 6.0.5 on 2026-05-07 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_userteam_free_transfers'),
    ]

    operations = [
        migrations.AddField(
            model_name='userteam',
            name='free_transfers',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
