# Generated by Codex on 2026-05-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_userteam_free_transfers'),
    ]

    operations = [
        migrations.AddField(
            model_name='userteam',
            name='watchlist',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='userteam',
            name='notifications',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
