# Generated by Codex on 2026-05-09

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_userteam_watchlist_notifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userteam',
            name='budget',
            field=models.DecimalField(decimal_places=2, default=Decimal('50000000.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='userteam',
            name='selected_players',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='userteam',
            name='weekly_points',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='userteam',
            name='rewards',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
