# Generated by Codex on 2026-05-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_team_selection_weekly_rewards_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='userteam',
            name='squads',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='userteam',
            name='active_squad_id',
            field=models.CharField(blank=True, default='default', max_length=64),
        ),
    ]
